language: python
env:
  - DJANGO_VERSION=1.8.0
  - DJANGO_VERSION=1.9.0
  - DJANGO_VERSION=1.10.0
  - DJANGO_VERSION=master
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  exclude:
    - python: "3.3"
      env: "DJANGO_VERSION=1.9.0"
    - python: "3.3"
      env: "DJANGO_VERSION=1.10.0"
    - python: "3.3"
      env: "DJANGO_VERSION=master"
install:
  - if [[ $DJANGO_VERSION != 'master' ]]; then pip install django~=$DJANGO_VERSION; else pip install -e git://github.com/django/django.git#egg=Django; fi
  - pip install .
script: ./test_project/manage.py test
